/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = number;
export type Name = string;
export type Data = DataRow[];

export interface DataResponse {
  data: Data;
  [k: string]: unknown;
}
export interface DataRow {
  id: Id;
  name: Name;
  [k: string]: unknown;
}
